### ISSUE TITLE
AC and DC

### ISSUE THREAD

**Issue by arshidkv12** [TG9541/stm8ef#199]
Hi,
I want to control AC and DC volt simultaneously. So can I take 12V from (board) relay input?
I will connect AC k0 and K1 as a switch.

**Comment by TG9541** [comment]
Hi Arshid, I have "little doubt" if I'm getting this correctly. 
Do you want to supply the board with 12V AC?

I guess that the board could be operated this way, but the resulting voltage after the diode would be about 6V as it would be just half of the AC cycle. Using a [diode bride])(https://en.wikipedia.org/wiki/Diode_bridge) would be better, but then the output voltage (about (12V-1V) * sqrt(2)) is a bit too high for the AM1117 voltage regulator. I would recommend that you use a diode bridge, and a 12V voltage regulator.

Best Regards,
Thomas

**Comment by arshidkv12** [comment]
Thank you 
Board input is 12v DC. I want control fan (12v DC) and bulb (220v ac) simultaneously.

**Comment by VK6TT** [comment]
Hi Arshid,The W1209 board isn't suitable for 220Volts in my opinion. And it cannot be used to control both the voltages at once since it is only a single pole relay. Regards Richard On 28 Apr. 2018 4:16 am, Arshid <notifications@github.com> wrote:Thank you
Board input is 12v DC. I want control fan (12v DC) and bulb (220v ac) simultaneously.

**Comment by TG9541** [comment]
@arshidkv12  , @VK6TT is right: the you can't control 220V AC and 12V DC with one relay contact. In stronger terms, you should never attempt to switch 220V AC or DC with the relay because the relay is rated 125V AC (hazard: fire), and I wouldn't call the PCB design safe for anything above 42V (hazard: electric shock).

You can, however, use the W1209 relay to control a 12V DC fan, and a suitable 220V relay (e.g. the [12V controlled relay here](https://www.aliexpress.com/item/one-1-channel-relay-module-5V-Low-level-trigger-Relay-Expansion-Board/32812326703.html) plus a proper insulation) at the same time.

**Comment by arshidkv12** [comment]
Can I replace 125vac relay to 220vac? 
Can I take 12v controled DC output from relay input (from board)

**Comment by arshidkv12** [comment]
How to connect relay module to thermostat. Vcc = 12v 
Input = k0, k1 Thermostat relay output (12v)

**Comment by TG9541** [comment]
The question about connecting the relay alone was answered in my last comment. 
The relay module should come with a description. It's possible that one of the control inputs needs to be connected to the common GND of fan, W1209, and 12V DC power supply, and the other control input to the switched W1209 relay output, together with the switched fan supply.

**Comment by arshidkv12** [comment]
Sorry... My doubt is how to connect new relay module to w1209

**Comment by TG9541** [comment]
I understand that :-) Just as I did with my last master student, also from Kerala, I'd like to ask you to read my answers carefully. You'll find the answers you're looking for.

**Comment by arshidkv12** [comment]
Sorry for my disturbance.
Please check circuit
![draw](https://user-images.githubusercontent.com/6806645/39393726-7b5940f2-4ae6-11e8-8058-faa8d7a45f3e.png)

**Comment by TG9541** [comment]
Very nice, this will work :-)

**Comment by arshidkv12** [comment]
Thank you..

**Comment by TG9541** [comment]
You're welcome. Success with your project!

**Comment by VK6TT** [comment]
Hi again ArshidYou have connected negative to the +12 point on the W1209. While you are on the right track perhaps you need to discuss this in person with someone who is experienced with lethal ac supplies. There is more to wiring up a circuit safely than just knowing where the wires go. It appears from your efforts to date you have yet to acquire the knowledge to play with lethal ac supplies. So sorry but I don't want to participate further in 220v ac matters. It's just too dangerous. Stick to 12v and live a lot longer. Kind regards Richard On 28 Apr. 2018 3:47 pm, Arshid <notifications@github.com> wrote:Sorry for my disturbance.
Please check circuit

**Comment by arshidkv12** [comment]
How to design circuit?
Protius or which software is using ?
I know programming in c, python and Java. Please refer me good videos or
books.

**Comment by TG9541** [comment]
This here might do the job:  https://www.aliexpress.com/item/Inkbird-AU-Plug-Digital-Temperature-Controller-Outlet-Thermostat-ITC-308-Heating-and-Cooling-Dual-Relay-For/32846188581.html

**Comment by arshidkv12** [comment]
I edited my circuit. Thank you
